#define STRIP_LENGTH 84
#define HALF_STRIP_LENGTH STRIP_LENGTH / 2
#define ARROW_STRIP_LENGTH 32
#define ARROWS_START 26
#define ARROWS_END 57

#define ARROW_LENGTH 8

#define ARROW_1_START 26
#define ARROW_1_END 33
#define ARROW_2_START 34
#define ARROW_2_END 41
#define ARROW_3_START 42
#define ARROW_3_END 49
#define ARROW_4_START 50
#define ARROW_4_END 57

#define ARROW_TRIGGER_1 2
#define ARROW_TRIGGER_2 5
#define ARROW_TRIGGER_3 8
#define ARROW_TRIGGER_4 11

#define SHOOT_TRAIL_START 14
#define SHOOT_TRAIL_END 25
#define TRAIL_LENGTH 4